FROM node:8.11.1

LABEL description="dcrweb build"
LABEL version="1.0"
LABEL maintainer "holdstockjamie@gmail.com"

USER root
WORKDIR /root

COPY ./ /root

RUN yarn global add grunt

CMD yarn install && \
    yarn run deploy:build && \
    cp -r /root/docker-build/. /docker-build/ && \
    chmod -R a+rwx /docker-build
