version: '2.1'
services:
  www:
    build:
      dockerfile: dockerfiles/www/Dockerfile
      context: .
    image: decred/dcrweb-www
    ports:
      - "8080:80"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080"]
        interval: 30s
        timeout: 10s
        retries: 5
    restart: always
    depends_on:
      api:
        condition: service_started


  api:
    build:
      dockerfile: dockerfiles/api/Dockerfile
      context: .
    image: decred/dcrweb-api
    ports:
      - "8081:80"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8081"]
        interval: 30s
        timeout: 10s
        retries: 5
