FROM httpd:alpine

LABEL description="dcrweb serve"
LABEL version="1.0"
LABEL maintainer "holdstockjamie@gmail.com"

COPY docker-build/ /var/www/html/

COPY runtime/httpd.conf        /usr/local/apache2/conf
COPY runtime/httpd-foreground  /usr/local/bin/
