#!/bin/bash

set -e

# Apache gets grumpy about PID files pre-existing
rm -f /usr/local/apache2/logs/httpd.pid
cp /usr/local/apache2/conf/httpd.conf /tmp

if [ -z $PORT ]; then
  PORT=80
fi

sed -i  "s/@PORT@/$PORT/" /tmp/httpd.conf

exec httpd  -f /tmp/httpd.conf -DFOREGROUND
