#!/bin/bash

set -e

# Apache gets grumpy about PID files pre-existing
rm -f /usr/local/apache2/logs/httpd.pid
cp /usr/local/apache2/conf/httpd.conf /tmp

# see if $PORT is set - otherwise use default 80
if [ -z $PORT ]; then
  PORT=80
fi

# replace @PORT@ tokens with actual port
sed -i  "s/@PORT@/$PORT/" /tmp/httpd.conf

exec httpd  -f /tmp/httpd.conf -DFOREGROUND
